# .github/FUNDING.yml

custom: ['https://paypal.me/rajkumarpandi']

If you found this project helpful, consider supporting it. Every contribution helps improve features, fix bugs faster, and keep this project available for everyone.
