# .github/FUNDING.yml
## 💖 Contribute or Sponsor

If you found this project helpful, consider supporting it:
custom: ['https://paypal.me/rajkumarpandi']

Every contribution helps improve features, fix bugs faster, and keep this project available for everyone.
